Find peer devices when start ranging.
google/pica pull request #43
Opened 2023-11-14 22:23 UTC by bobwzy

2023-11-14 22:48 UTC, SilverBzH requested changes

2023-11-14 22:48 UTC, SilverBzH commented on src/session.rs
> +    pub fn can_start_ranging_with_peer(&self, peer_config: Self) -> bool {
We could implement [PartialEq](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html) and just add the additional comparison in this function

2023-11-14 23:15 UTC, hchataing commented on src/lib.rs
> +        &self,
self is unused, does this function need to be a method ?

2023-11-14 23:28 UTC, hchataing commented on src/lib.rs
> +                    self.get_device_by_mac(*mac_address, session.app_config.clone(), session_id)
Can you pass the AppConfig by reference instead ? AppConfig is not small

2023-11-14 23:29 UTC, hchataing commented on src/lib.rs
> +                    && local_app_config.can_start_ranging_with_peer(&session.app_config.clone())
clone not necessary here, you already take a reference

2023-11-15 00:36 UTC, SilverBzH approved these changes

2023-11-15 00:53 UTC, hchataing commented on src/lib.rs
> +fn add_measurement(
nit: 
I would rather have this function be `make_measurement`, though it might not work as well when long addresses are used in the measurements.
```
fn make_measurement(mac_address: &MacAddress, local: (u16, i16, i8), , local: (u16, i16, i8))
 -> ShortAddressTwoWayRangingMeasurement
```
And in callers:
```
measurements.push(make_measurement(address, local, remote)
```
You could also add a specific constructor for `ShortAddressTwoWayRangingMeasurement` in packets.rs.

2023-11-15 00:54 UTC, hchataing commented on src/lib.rs
> +        mac_address: MacAddress,
`&MacAddress`

2023-11-15 00:57 UTC, hchataing commented on src/session.rs
> +impl PartialEq for AppConfig {
You should be able to derive the implementation in the type definition, or am I missing a subtlety ?

2023-11-15 00:59 UTC, hchataing commented on src/session.rs
> +    pub fn get_session_state(&self) -> SessionState {
`session_state` is more rusty

2023-11-15 01:02 UTC, hchataing commented on src/session.rs
> +    pub fn get_device_mac_address(&self) -> MacAddress {
I prefer that you make the parameter public since we are passing the AppConfig by immutable reference

2023-11-15 17:30 UTC, hchataing approved these changes
Thanks ! Can you squash the commits before uploading please ?

2023-11-15 17:39 UTC, merged