Add data transfer functionality
google/pica pull request #44
Opened 2023-11-17 00:17 UTC by hasanawais

Implement support for FIRA 2.0 data transfer

2023-11-22 23:09 UTC, SilverBzH requested changes

2023-11-22 23:09 UTC, SilverBzH commented on src/lib.rs
> +            }
Here we can do pattern matching to avoid mutable variable:
```suggestion
            let payload_length = match header.get_mt() {
                MessageType::Data => usize::from_le_bytes(complete_packet[2..3].try_into().unwrap()),
                _ =>  header.get_payload_length() as usize
            };
```

2023-11-22 23:09 UTC, SilverBzH commented on src/lib.rs
> +            Err(_) => UciParseResult::Skip,
Usually we put the `Ok` field in first position

2023-11-22 23:09 UTC, SilverBzH commented on src/lib.rs
> +    let message_type = (bytes[0] >> 5) & 0x7;
A comment would be nice as well. But If we're doing this more than once then maybe we can create an helper function

2023-11-27 23:56 UTC, hchataing commented on src/lib.rs
> +            let mut payload_length = header.get_payload_length() as usize;
I think it is necessary to change the expectations the function first to account for the differences between data and control packets.

- Control and data packets have a different header (payload size is larger for data packets)
- Data packets have flow control that is session specific, ie. each individual fragment must be acknowledged at the session level.

As I see it, 
control packet reassembly could still be performed in this function, with the caveat that interspersing data and control segments will not be supported (sounds reasonable), but data packet reassembly must be performed by the session.

Can you update the function comment and implementation to reflect this ?
An option would be to change the return type to make that explicit:

```
enum Packet {
  Control (Vec<u8>),
  DataSegment(Vec<u8>),
}
```

2023-11-28 00:24 UTC, hchataing commented on src/lib.rs
> +    Ok {
This part will probably change, but you should use a stricter pattern for expressing this:
```
enum UciParseResult {
   UciCommand(UciCommand),
   UciData(UciDataPacket),
   Err(Bytes),
   Skip,
}
```
This expresses better the constraint that exactly one of uci_command and uci_data_packet must be present.

2023-11-28 00:37 UTC, hchataing commented on src/uci_packets.pdl
PacketHeader is not compatible for Control and Data packets and should be updated:

```
// Used to parse message type
packet PacketHeader {
  _reserved_ : 4,
  pbf : PacketBoundaryFlag,
  mt : MessageType,
}

// Used to parse control packet length
packet ControlPacketHeader {
  _reserved_ : 4,
  pbf : PacketBoundaryFlag,
  mt : MessageType,
  _reserved_ : 16,
  payload_length : 8,
}

// Used to parse data packet length
packet DataPacketHeader {
  _reserved_ : 4,
  pbf : PacketBoundaryFlag,
  mt : MessageType,
  _reserved_ : 8,
  payload_length : 16,
}
```

2023-11-28 00:50 UTC, hchataing commented on src/lib.rs
> +                Some(DataTransfer(device_handle, data)) => (),
Use `todo!` to mark unfinished parts of the code.

2023-11-28 00:53 UTC, hchataing commented on src/lib.rs
> +            PicaCommand::DataTransfer(_, _) => "DataTransfer",
`DataTransfer` is ambiguous as a name as it could be interpreted as the effective data transfer (from device to device), when it is just data transfer over UCI (from host to uwbs).

Two options:
1. change `Command` to `UciPacket` and modify the parameter to be a union of Command, Data
2. add `UciData` and rename `Command` to `UciCommand` for homogeneity

2023-11-29 23:42 UTC, hasanawais commented on src/session.rs
> +        // assert_eq!(self.session_type, SessionType::FiraRangingSession);
I'm going to hold off on removing other session types in the pdl for now, but we can revisit this if need be.

2023-11-29 23:44 UTC, hasanawais commented on src/lib.rs
> +            let message_type = (header_bytes[0] >> 5) & 0x7;
Added comment to get_message_type helper function

2023-11-29 23:47 UTC, hasanawais commented on src/lib.rs
> +    let message_type = (bytes[0] >> 5) & 0x7;
Added comment to get_message_type helper function

2023-11-29 23:48 UTC, hasanawais commented on src/lib.rs
> +const MAX_DATA_PAYLOAD_SIZE: usize = 1024;
I changed the name for the data packets, but forgot for the control ones. Will address in next commit

2023-11-29 23:50 UTC, hasanawais commented on src/lib.rs
> +            PicaCommand::DataTransfer(_, _) => "DataTransfer",
I went with option 2, thanks

2023-11-30 17:54 UTC, hchataing commented on src/uci_packets.pdl
> +packet UciPacketHal {
I would prefer not using `Hal` as it is connotative of android.
I am not sure that you need to have these definitions either, since the packet header is used for parsing.
Preferably, the change would be minimal and add only:

```
packet DataPacket {
  dpf : DataPacketFormat,
  pbf : PacketBoundaryFlag,
  _fixed_ = 0x0 : 3, // Message type = data (or mt: MessageType up to your preference)
  _reserved_ : 8,
  _reserved_ : 16,
  _payload_,
}

// Changed the naming of fields to conform to UCI 2.0 specification.
packet DataMessageSnd : DataPacket (dpf = DATA_MESSAGE_SND) {
    session_handle: 32,
    destination_address: 64,
    data_sequence_number: 16,
    _size_(application_data): 16,
    application_data: 8[]
}

packet DataMessageRcv : DataPacket (dpf = DATA_MESSAGE_RCV) {
    session_handle: 32,
    status : StatusCode, 
    source_address: 64,
    data_sequence_number: 16,
    _size_(application_data): 16,
    application_data: 8[]
}
```

2023-11-30 17:54 UTC, hchataing commented on src/uci_packets.pdl
> +packet UciCommand : UciControlPacket (message_type = COMMAND) {
Please avoid renaming the fields / packets in the same pull request.
I would rather have a separate change for this.

2023-11-30 17:54 UTC, hchataing commented on src/lib.rs
>  const MAX_PAYLOAD_SIZE: usize = 255;
Please rename to `MAX_CTRL_PACKET_PAYLOAD_SIZE`

2023-11-30 17:54 UTC, hchataing commented on src/lib.rs
>      async fn read(&mut self) -> Result<Vec<u8>> {
```suggestion
    /// Read a single UCI packet from the socket.
    /// Control packets are automatically re-assembled if segmented on the UCI transport.
    /// Data packets fragments are returned immediately, as each fragment needs to be
    /// acknowledged by a credit notification.
    async fn read(&mut self) -> Result<Vec<u8>> {
```

2023-11-30 17:54 UTC, hchataing commented on src/lib.rs
> +            let payload_length = match header.get_mt() {
This code is still in practice re-assembling data packets. You should exit when receiving a data packet fragment.

2023-11-30 17:54 UTC, hchataing commented on src/lib.rs
> +            };
```suggestion
            let chunk_length = std::min(packet.len(), match MessageType::try_from(message_type) {
                Ok(MessageType::Data) => MAX_DATA_PACKET_PAYLOAD_SIZE,
                _ => MAX_PAYLOAD_SIZE            
            });
```

2023-11-30 17:54 UTC, hchataing commented on src/lib.rs
> +}
To simplify the code in `Connection::write`:
```suggestion
fn get_message_type(byte: u8) -> MessageType {
    MessageType::try_from((byte >> 5) & 0x7).unwrap_or(MessageType::Control)
}
```

2023-11-30 17:54 UTC, hchataing commented on src/device.rs
> +        data_tx: mpsc::Sender<SessionControlNotification>,
I am not sure that you need this separate `data_tx` channel. You can send the `SessionControlNotification` through the existing `tx`.

2023-11-30 17:54 UTC, hchataing commented on src/device.rs
> +    pub fn command_data_transfer(&mut self, data: UciDataPacketHal) -> SessionControlNotification {
nit: Rename to `data_message_snd` to match UCI specification ?

2023-12-06 18:34 UTC, SilverBzH submitted a review, later dismissed

2023-12-06 18:34 UTC, SilverBzH commented on src/lib.rs
> +                    header_bytes[3] = high;
nit (just to save a line):
```suggestion
                    let chunk_le_bytes = (chunk_length as u16).to_le_bytes();
                    header_bytes[2..4].copy_from_slice(&chunk_le_bytes);
```

2023-12-06 18:34 UTC, SilverBzH commented on src/device.rs
> +                // Add graceful failure, ideally with a DataTransferNtfStatusCode
Agree

2023-12-06 18:34 UTC, SilverBzH commented on src/session.rs
> +            self.session_type != SessionType::FiraDataTransferSession {
We're asserting previously the session should only be `FiraRangingSession` or `FiraRangingAndInBandDataSession` hence it might not be possible to be `FiraDataTransferSession` right ?

2023-12-06 18:34 UTC, SilverBzH commented on src/session.rs
> +                tx_count: 1, // TODO: support for retries?
We can leave it as is for now I guess

2023-12-06 23:08 UTC, hasanawais commented on scripts/console.py
> +def encode_session_id(session_id: str) -> bytes:
This function is not needed anymore

2023-12-06 23:11 UTC, hasanawais commented on src/lib.rs
> +
unneeded, will fix in next commit

2023-12-06 23:14 UTC, hasanawais commented on src/lib.rs
> +            let chunk_length = std::cmp::min(packet.len(), match MessageType::try_from(message_type) {
`MessageType::try_from` is unnecessary due to `get_message_type` return, will fix in next commit

2023-12-13 18:23 UTC, hchataing commented on src/lib.rs
> +                                    ReadPacket::Control(rp) | ReadPacket::DataSegment(rp) => {
You lose the advantage of defining  `DataSegment` and `Control` here by converging to the same code path again. You could specialize `parse_uci_packet` with one version for control, another for data packtes.

2023-12-13 18:26 UTC, hchataing commented on src/session.rs
> +    credit_availability: CreditAvailability,
I would initially ignore the credit availability in the session state, and suppose that credit is always available.
That will simplify the logic, until we actually implement something useful with credits.

2023-12-13 21:48 UTC, hchataing commented on src/device.rs
> +                todo!()
:thinking:  you will need to extract the session handle manually.
In this case I would suggest implementing the case for DataMessageRcv (which does have the session_handle), and leave the default case as `unimplemented!`

2023-12-14 22:35 UTC, hchataing commented on src/device.rs
> +                    return session.data_message_snd(data_msg_snd);
nit: `return` is unnecessary here (and other places in the function)

2023-12-14 22:35 UTC, hchataing commented on src/session.rs
> +        return DataCreditNtfBuilder {
nit: `return` not necessary here

2023-12-15 01:59 UTC, hchataing approved these changes

2023-12-15 17:18 UTC, SilverBzH approved these changes

2023-12-15 19:53 UTC, merged