Simulate the case when controller remove a controlee.
google/pica pull request #46
Opened 2023-11-17 19:25 UTC by bobwzy

When a controller removes a controlee, the controlee should stop ranging
automatically instead waiting for a timeout. So added a new PicaCommand to
achieve this.

Also remove the AppConfig that only applicable for controller from AppConfig
matching.

2023-11-28 19:26 UTC, hchataing requested changes

2023-11-28 19:26 UTC, hchataing commented on src/lib.rs
> +    async fn stop_controlee_ranging(
Same, please add some context here describing what this function is emulating.

2023-11-28 19:26 UTC, hchataing commented on src/lib.rs
> +    // Stop ranging session with certain session id and app config.
`Send an in-band request to stop ranging to a peer controlee identified by address`
I am not sure why the session id and app config would be required here, can you expand ?
You would need to controller address though.

2023-11-28 19:26 UTC, hchataing commented on src/session.rs
> +                                    session_id,
The session ID should be the session ID on the controlee device, not the local session ID.
Same for the App config.

2023-11-28 22:57 UTC, bobwzy commented on src/lib.rs
> +    // Stop ranging session with certain session id and app config.
I supposed we need the session id to get the corresponding session on Controlee side. But it is not mentioned in the spec, so  seems the session_id doesn't have to be identical on both sides?

Then maybe use controller address is enough.

2023-11-28 22:58 UTC, hchataing commented on src/lib.rs
> +    // Stop ranging session with certain session id and app config.
I assume the session id is local to the uwbs instance, and not shared over the air, but I may be wrong as I have not read into the exact exchange format.

2023-11-28 23:34 UTC, bobwzy commented on src/lib.rs
> +    // Stop ranging session with certain session id and app config.
There's the definition in the CSML spec:
UWB Session ID: A 32bit unique integer identifying a UWB Session, shared between Controller and Controlee.
https://groups.firaconsortium.org/wg/Technical/document/2415

So I think using session_id to find the session is sufficient.

2023-11-29 18:10 UTC, hchataing commented on src/lib.rs
> +    // Stop ranging session with certain session id and app config.
Ok, but then I am not certain we properly implement session ID management in Pica.
From what I am reading the controller session ID is used as identifier for the session.

2023-11-29 18:11 UTC, hchataing commented on src/lib.rs
> +    // Stop ranging session with certain session id and app config.
I am not certain what happens to the session ID on the controlee side

2023-11-30 17:58 UTC, bobwzy commented on src/session.rs
> +                                    session_id,
Removed the app config. As discussed above I think we can use session id to get the session we want.

2023-12-04 19:05 UTC, merged