Refactor packet framing to support generic streams
google/pica pull request #51
Opened 2023-12-22 07:46 UTC by hchataing

- introduce packets::nci::Reader and packets::nci::Writer
  which wrap around dyn AsyncRead and dyn AsyncWrite respectively
- the methods Reader::read and Writer::write perform the logic
  previoulsy implemented in Conntection::read and Connection::write

2023-12-28 10:45 UTC, SilverBzH commented on src/lib.rs
> +
Could be nice to keep the `Connection` object to wrap up the reader and the writer. It'll gather the uci_x under a common object and manipulate a connection instead of rx/tx.

2023-12-28 10:49 UTC, hchataing commented on src/lib.rs
> +
The connection object does present a useful abstraction anymore, it would just be implemented as pass-through for read and write. Furthermore it would only be constructed on the stack within the future.

2024-01-02 16:24 UTC, DeltaEvo requested changes

2024-01-02 16:24 UTC, DeltaEvo commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
Why not make Reader generic over something implementing AsyncRead?

The two halves of a splited TcpStream have exposed types [OwnedReadHalf](https://docs.rs/tokio/latest/tokio/net/tcp/struct.OwnedReadHalf.html#)/[OwnedWriteHalf](https://docs.rs/tokio/latest/tokio/net/tcp/struct.OwnedWriteHalf.html#)

2024-01-02 16:24 UTC, DeltaEvo commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
Is the Mutex needed, can you not make `read` and `write` take `&mut` ?

2024-01-02 16:24 UTC, DeltaEvo commented on src/pcapng.rs
> +    file: Arc<Mutex<tokio::fs::File>>,
I think it would make more sense to put the `Arc<Mutex<` inside the reader and writer.

Also are we able to avoid it altogether by passing the `pcapng::File` as `&mut` argument of `Reader::read` and `Writer::write`?

2024-01-02 16:31 UTC, hchataing commented on src/pcapng.rs
> +    file: Arc<Mutex<tokio::fs::File>>,
> I think it would make more sense to put the Arc<Mutex< inside the reader and writer.

I initially did that, but since the reader and writer share the pcapng file instance, the mutex needs to be present in the signature of NciReader::new, NciWriter::new. Given this, I find it cleaner to move the mutex to Pcapng rather than using `pub fn new(/**/, pcapng: Option<Arc<Mutex<pcapng::File>>>)`

> Also are we able to avoid it altogether by passing the pcapng::File as &mut argument of Reader::read and Writer::write?

I cannot pass the same &mut to both

2024-01-02 16:38 UTC, DeltaEvo commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
Or even no need to make it generic just put `OwnedReadHalf` 😅

2024-01-02 16:41 UTC, hchataing commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
Still linked to tcp. If possible I would like to be able to craft a mock version for testing purposes

2024-01-02 16:45 UTC, DeltaEvo commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
> may be used multiple times

Do you plan to do something like that in the future?

Because right now it should not be the case with tokio::select

```diff
diff --git a/src/lib.rs b/src/lib.rs
index bdc1c55..2633edd 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -360,7 +360,7 @@ impl Pica {

             let (uci_rx, uci_tx) = stream.into_split();
             let uci_reader = packets::uci::Reader::new(uci_rx, pcapng_file.clone());
-            let uci_writer = packets::uci::Writer::new(uci_tx, pcapng_file);
+            let mut uci_writer = packets::uci::Writer::new(uci_tx, pcapng_file);

             'outer: loop {
                 tokio::select! {
diff --git a/src/packets.rs b/src/packets.rs
index c6d1f97..24c7cd2 100644
--- a/src/packets.rs
+++ b/src/packets.rs
@@ -137,7 +137,7 @@ pub mod uci {

         /// Write a single UCI packet to the writer. The packet is automatically
         /// segmented if the payload exceeds the maximum size limit.
-        pub async fn write(&self, mut packet: &[u8]) -> anyhow::Result<()> {
+        pub async fn write(&mut self, mut packet: &[u8]) -> anyhow::Result<()> {
             use tokio::io::AsyncWriteExt;

             let mut socket = self.socket.lock().await;
```

On top of your PR compiles successfully

2024-01-02 16:48 UTC, hchataing commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
Ok, lets change it when we do need concurrent use :+1:

2024-01-02 16:49 UTC, DeltaEvo commented on src/pcapng.rs
> +    file: Arc<Mutex<tokio::fs::File>>,
> I cannot pass the same &mut to both

Just tried locally and it works just file, the magic of tokio::select 🙃

2024-01-02 16:50 UTC, DeltaEvo commented on src/pcapng.rs
> +    file: Arc<Mutex<tokio::fs::File>>,
<details>
```diff
diff --git a/src/lib.rs b/src/lib.rs
index bdc1c55..072e11a 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -350,7 +350,7 @@ impl Pica {
         // The task notifies pica when exiting to let it clean
         // the state.
         tokio::task::spawn(async move {
-            let pcapng_file = if let Some(dir) = pcapng_dir {
+            let mut pcapng_file = if let Some(dir) = pcapng_dir {
                 let full_path = dir.join(format!("device-{}.pcapng", device_handle));
                 println!("Recording pcapng to file {}", full_path.as_path().display());
                 Some(pcapng::File::create(full_path).await.unwrap())
@@ -360,7 +360,7 @@ impl Pica {

             let (uci_rx, uci_tx) = stream.into_split();
             let uci_reader = packets::uci::Reader::new(uci_rx, pcapng_file.clone());
-            let uci_writer = packets::uci::Writer::new(uci_tx, pcapng_file);
+            let uci_writer = packets::uci::Writer::new(uci_tx);

             'outer: loop {
                 tokio::select! {
@@ -377,7 +377,7 @@ impl Pica {
                                         pica_tx.send(PicaCommand::UciData(device_handle, data)).await.unwrap()
                                     },
                                     UciParseResult::Err(response) =>
-                                        uci_writer.write(&response).await.unwrap(),
+                                        uci_writer.write(&response, &mut pcapng_file).await.unwrap(),
                                     UciParseResult::Skip => (),
                                 },
                             Err(_) => break 'outer
@@ -385,7 +385,7 @@ impl Pica {

                     // Send response packets to the connected UWB host.
                     Some(packet) = packet_rx.recv() =>
-                        if uci_writer.write(&packet.to_bytes()).await.is_err() {
+                        if uci_writer.write(&packet.to_bytes(), &mut pcapng_file).await.is_err() {
                             break 'outer
                         }
                 }
diff --git a/src/packets.rs b/src/packets.rs
index c6d1f97..f111855 100644
--- a/src/packets.rs
+++ b/src/packets.rs
@@ -55,7 +55,6 @@ pub mod uci {
     /// Performs segmentation of the packets.
     pub struct Writer {
         socket: Mutex<Pin<Box<dyn AsyncWrite + Send>>>,
-        pcapng: Option<pcapng::File>,
     }

     impl Reader {
@@ -128,16 +127,15 @@ pub mod uci {

     impl Writer {
         /// Create an UCI writer from an UCI transport.
-        pub fn new<T: AsyncWrite + Send + 'static>(rx: T, pcapng: Option<pcapng::File>) -> Self {
+        pub fn new<T: AsyncWrite + Send + 'static>(rx: T) -> Self {
             Writer {
                 socket: Mutex::new(Box::pin(rx)),
-                pcapng,
             }
         }

         /// Write a single UCI packet to the writer. The packet is automatically
         /// segmented if the payload exceeds the maximum size limit.
-        pub async fn write(&self, mut packet: &[u8]) -> anyhow::Result<()> {
+        pub async fn write(&self, mut packet: &[u8], pcapng: &mut Option<pcapng::File>) -> anyhow::Result<()> {
             use tokio::io::AsyncWriteExt;

             let mut socket = self.socket.lock().await;
@@ -171,7 +169,7 @@ pub mod uci {
                     _ => header_bytes[3] = chunk_length as u8,
                 }

-                if let Some(ref pcapng) = self.pcapng {
+                if let Some(ref pcapng) = pcapng {
                     let mut packet_bytes = vec![];
                     packet_bytes.extend(&header_bytes);
                     packet_bytes.extend(&packet[..chunk_length]);
```
</details>

2024-01-02 16:53 UTC, hchataing commented on src/pcapng.rs
> +    file: Arc<Mutex<tokio::fs::File>>,
Looks nice right now, but will be painful if we move away from the mpsc channel for writing packets in the future.
What do you think ?

2024-01-02 17:28 UTC, DeltaEvo commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
Then generics are the way to go :)

2024-01-02 17:31 UTC, DeltaEvo commented on src/pcapng.rs
> +    file: Arc<Mutex<tokio::fs::File>>,
I think it's better to always put the synchronization at the highest layer (the one that needs it), so if we remove the mpsc channel and that we need a Mutex we should put it on top of the Writer, not inside the Writer to allow to see if it's needed more easily and remove it if not.

It's a bit the same logic than https://matklad.github.io/2023/11/15/push-ifs-up-and-fors-down.html

2024-01-03 10:09 UTC, hchataing commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
Done

2024-01-03 10:19 UTC, hchataing commented on src/pcapng.rs
> +    file: Arc<Mutex<tokio::fs::File>>,
done

2024-01-03 10:22 UTC, hchataing commented on src/packets.rs
> +        socket: Mutex<Pin<Box<dyn AsyncRead + Send>>>,
Nope

2024-01-16 19:24 UTC, DeltaEvo approved these changes

2024-01-16 19:25 UTC, merged