Update version for tokio, num-derive, pdl-runtime to satisfy CMake build with netsim
google/pica pull request #60
Opened 2024-01-24 18:55 UTC by hyunjaemoon-work

2024-01-24 19:10 UTC, hyunjaemoon-work commented
This change is necessary to build pica and netsim with CMake build

2024-01-24 19:47 UTC, SilverBzH commented
I am not really a fan of downgrading the version. I would prefer netsim to adapt to the newest version instead of rolling back

2024-01-24 19:48 UTC, SilverBzH requested changes
I am not really a fan of downgrading the version. I would prefer netsim to adapt to the newest version instead of rolling back.

2024-01-24 19:59 UTC, SilverBzH commented
If I  am correct Pica will be used as a library within netsim.

Is Netsim built with soong ? If so then we don't need to change the cargo.toml. Pica has is own soong file to make it build within android and use it as a lib: https://cs.android.com/android/platform/superproject/main/+/main:external/rust/pica/Android.bp

2024-01-24 20:21 UTC, hyunjaemoon-work commented
That is correct! We intend to use pica as the uwb library for netsim.

Netsim uses Soong build to support cuttlefish (which builds well already) and uses CMake build to support goldfish (which needs this PR). And the CMake build is necessary to support different OS and the versions must match to satisfy corrosion, and the Cargo.toml is being actively used in this case.

2024-01-24 21:00 UTC, SilverBzH commented
Ok I understand.

A good solution might be to update the `Cargo.toml` within the Android directory directly to manage the Android's dependency and let this one untouched.

We can maintain the flexibility to update the dependency strategically when a Pica release makes it necessary. If the original Pica's dependencies are locked by the one on Android it could be an issue for its development.

2024-01-24 21:28 UTC, hchataing commented
I prefer applying the change to the source repository instead of making untracked changes to the external/rust/pica repository. We do need to pay attention to avoid breaking this again in the future.

2024-01-24 21:49 UTC, SilverBzH commented
I disagree.

We already are in a situation where the dependencies are different and it is untracked with the `Android.bp`, it would just remain the same.

There are couple of way to track this, one way could be to have a copybara presubmit to check if for any change Pica is well building on the Android side.

And if it is not building and the dependency is really needed, then the dependency shall be update on the Android side.

2024-01-24 21:54 UTC, hyunjaemoon-work commented
Perhaps this might be useful to allow multiple versions as Android Rust Team has suggested:

https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#using-patch-with-multiple-versions

2024-01-24 22:31 UTC, SilverBzH commented
If overriding the version with the `[patch]` directive works then I am down for this solution.

2024-01-25 00:36 UTC, hyunjaemoon-work commented
Unfortunately the overwriting of version with [patch] directive wouldn't work as it is unable to refer crate paths in aosp from an isolated environment nor we are not allowed to pull crates from external URL into aosp.

I've attempted multiple different solutions such as using the caret requiremtn `pdl-runtime = ^0.2.2` as well as setting feature flags with optional dependencies for num-derive, (older version to be used when `android` flag is raised and newer version to be used by default), but it failed to satisfy our CMake with corrosion builds.

From what I see, the best solution here seems to be updating the Rust crates in Android direclty for `num-derive` and `pdl-runtime`. 

I've uploaded a new commit for an upgrade of tokio crate version.

2024-01-25 00:44 UTC, SilverBzH commented
Ok, thanks to have taken the time to test it.

We discussed this offline with Henri and David. Since the majority approves, we're moving forward with this PR to prevent issues with multiple versions of Cargo.toml.

You can proceed by addind older version and we'll update Pica with this PR afterwards

2024-01-25 00:54 UTC, SilverBzH approved these changes

2024-01-25 00:59 UTC, hyunjaemoon-work commented
I don't have write access, so feel free to merge this PR at your convenience!

Thank you for approving this PR :)

2024-01-25 01:21 UTC, merged